name: med
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio:
  flutter_riverpod:
  flutter_secure_storage:
  flutter_native_splash:
  google_nav_bar:
  line_icons:
  carousel_slider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#0D142E"
  image: assets/images/logo.png

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PoppinsBlack
      fonts:
        - asset: fonts/Poppins-Black.ttf
    - family: PoppinsBold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: fonts/Poppins-ExtraBold.ttf
    - family: PoppinsExtraLight
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
    - family: PoppinsItalic
      fonts:
        - asset: fonts/Poppins-Italic.ttf
    - family: PoppinsLight
      fonts:
        - asset: fonts/Poppins-Light.ttf
    - family: PoppinsMedium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: PoppinsThin
      fonts:
        - asset: fonts/Poppins-Thin.ttf
